### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by alexkoss** [VladSKN/Docker_compose_cassandra#1]
Добрый день, Владислав. Меня зовут Александр, представитель БалтИнфоКом.

Представим сеть из машин А и Б. На машине А поднято три контейнера. Необходимо подключиться cqlsh с машины Б на второй контейнер. Пусть на А и Б будут ip 192.168.1.*

**Comment by VladSKN** [comment]
Добрый день! Александр, создал pull request. внес изменения. https://github.com/VladSKN/Docker_compose_cassandra/pull/2/files
проверьте пожалуйста как будет время

**Comment by alexkoss** [comment]
@VladSKN не работает

```
sentinel@sentinel-vm22:~/test/ldap/VladSKN/ansible-ldap-script-iss01$ ansible-playbook playbook-ldap.yml -i hosts --ask-become-pass
BECOME password:

PLAY [Установка OpenLDAP сервера и настройка] *******************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [client01]

TASK [Установка OpenLDAP сервера] *******************************************************************************************************************************************************
ok: [client01]

TASK [Запустить службу OpenLDAP] ********************************************************************************************************************************************************
ok: [client01]

TASK [debconf] **************************************************************************************************************************************************************************
ok: [client01]

TASK [Создание и установка пароля администратора] ***************************************************************************************************************************************
[DEPRECATION WARNING]: Encryption using the Python crypt module is deprecated. The Python crypt module is deprecated and will be removed from Python 3.13. Install the passlib library
for continued encryption functionality. This feature will be removed in version 2.17. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [client01]

TASK [Создание записи пользователя user1] ***********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ldap.UNDEFINED_TYPE: {'desc': 'Undefined attribute type', 'info': 'bind_dn: AttributeDescription contains inappropriate characters'}
fatal: [client01]: FAILED! => {"changed": false, "details": "{'desc': 'Undefined attribute type', 'info': 'bind_dn: AttributeDescription contains inappropriate characters'}", "msg": "Entry action failed."}

PLAY RECAP ******************************************************************************************************************************************************************************
client01                   : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```


c -vvv:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ldap_entry_payload_x2dgf2l5/ansible_ldap_entry_payload.zip/ansible_collections/community/general/plugins/modules/ldap_entry.py", line 278, in main
  File "/tmp/ansible_ldap_entry_payload_x2dgf2l5/ansible_ldap_entry_payload.zip/ansible_collections/community/general/plugins/modules/ldap_entry.py", line 198, in _add
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 430, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 416, in add_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 748, in result3
    resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 758, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.UNDEFINED_TYPE: {'desc': 'Undefined attribute type', 'info': 'bind_dn: AttributeDescription contains inappropriate characters'}
fatal: [client01]: FAILED! => {
    "changed": false,
    "details": "{'desc': 'Undefined attribute type', 'info': 'bind_dn: AttributeDescription contains inappropriate characters'}",
    "invocation": {
        "module_args": {
            "attributes": {
                "bind_dn": "cn=admin,CN=slapd,DC=example,DC=com",
                "bind_pw": "myadminpassword",
                "cn": "user1",
                "gidNumber": 55,
                "homeDirectory": "/home/test",
                "objectClass": [
                    "top",
                    "account",
                    "posixAccount",
                    "shadowAccount",
                    "person",
                    "inetOrgPerson"
                ],
                "server_uri": "ldap://localhost",
                "state": "present",
                "uid": "user1",
                "uidNumber": 157,
                "userPassword": "secretpass"
            },
            "bind_dn": null,
            "bind_pw": "",
            "ca_path": null,
            "dn": "cn=user1,CN=slapd,DC=example,DC=com",
            "objectClass": [
                "top",
                "account",
                "posixAccount",
                "shadowAccount",
                "person",
                "inetOrgPerson"
            ],
            "recursive": false,
            "referrals_chasing": "anonymous",
            "sasl_class": "external",
            "server_uri": "ldapi:///",
            "start_tls": false,
            "state": "present",
            "validate_certs": true,
            "xorder_discovery": "auto"
        }
    },
    "msg": "Entry action failed."
}

PLAY RECAP ******************************************************************************************************************************************************************************
client01                   : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


```
